theme: jekyll-theme-minimal
show_downloads: false
title: Zhang Yu Jie (Dominik)
position: Undergraduate Student
affiliation: University of Michigan, Ann Arbor
affiliation_link: https://umich.edu/
affiliation_logo: ./assets/img/university-of-michigan-3.svg


keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
enable_hopkins_logo: true


